### ISSUE TITLE
Get  Pangesture Direction

### ISSUE THREAD

**Issue by ManuPerfo** [sovata8/RevealingTableViewCell#10]
How can we get the direction for the cell movement ?

**Comment by sovata8** [comment]
I am not sure I understand your question. Do you mean "How do I define which directions the cell should swipe in?" ? In that case, the answer is that the supported "swipe" directions are determined by which of the "revealed" `IBOutlets` you connect in Interface Builder. So if you just connect `uiView_revealedContent_left`, then the cell will only be swipe-able to the right. If you connect both views, the cell will be swipe-able in both directions. Does this answer your question?

**Comment by sovata8** [comment]
Closed after 2 months of inactivity. I hope the answer provided was helpful.
