### ISSUE TITLE
The library would not work if storyaboards/xibs are not used

### ISSUE THREAD

**Issue by LeoNatan** [sovata8/RevealingTableViewCell#5]
You are using `awakeFromNib` for logic, but that method is only called when a storyboard/xib is used. You should instead support cases where UI is built in code.

There are other issues with your code. You are adding a gesture recognizer to (terribly named) `uiView_mainContent`, but the setter of that property is public. If the user replaces that view during runtime, your logic would be broken.

**Comment by sovata8** [comment]
Thanks for opening these issues, LeoNatan. Could you please separate this into two issues (so edit this one and open a new one) - so we can handle them separately. Thanks.

**Comment by LeoNatan** [comment]
I think two are correlated. The way it is currently handled in `awakeFromNib` will have the second issue, but changing it should take into account the first issue.

**Comment by sovata8** [comment]
Yes you're right it would make sense to tackle these together. I'll have a look when I have time, thanks.

**Comment by sovata8** [comment]
I've decided to keep this project focused on its main point of being usable with zero-code setup, via Storyboard/IB. So this issue/feature will not be in scope for now. Subject to review if others vote for it of course.
