### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by vladislav-m** [sovata8/RevealingTableViewCell#8]
I used RevealingTableViewCell for swift 4 project and got only one error during build time: 

> Pods/RevealingTableViewCell/RevealingTableViewCell/RevealingTableViewCell.swift:158:75: Argument of '#selector' refers to instance method 'selector_panGesture' that is not exposed to Objective-C

By adding `@objc` modifier to `selector_panGesture` this error was fixed. So it is pretty easy to make this library support swift 4, let's do this!

**Comment by vladislav-m** [comment]
By the way, here is my fork, containing this changes https://github.com/vladislav-m/RevealingTableViewCell

**Comment by vladislav-m** [comment]
And also pull request https://github.com/sovata8/RevealingTableViewCell/pull/9

**Comment by sovata8** [comment]
Using a Swift 3 library in a Swift 4 project should work without any issues. (I just tested this and it worked for me.)

Nonetheless, I definitely agree with the need to update to Swift 4 and thanks for doing it already!

Further discussion will take place on the Pull Request, so I'll close this issue now.
